projects/demo.yml
u2020-mvp is demo project that demostrates usage of Dagger 2, Espresso 2 and many other libraries alongside with MVP pattern.
=> Add demo project u2020-mvp

projects/free.yml
I have added [Decor](https://github.com/chemouna/decor) in the styling section
=> Add Decor library

README.md, projects/free.yml
Adding Slim Repo OSS project: https://github.com/slim-gears/slimrepo
=> Including Slim Repo OSS project

projects/free.yml
A tool to recover your lost keystore password
=> Adds Android Keystore Recovery

projects/free.yml
ContentLoadingProgressDialog from https://github.com/tasomaniac/ContentLoadingProgressDialog is added.
=> Added ContentLoadingProgressDialog library

projects/demo.yml
Simple example showing how to use WearableListview for Android Wear
=> Wearable Listview Example added

projects/free.yml
Add 1 more library from https://github.com/rockerhieu/rv-adapter-states.
=> Add `StatesRecyclerViewAdapter`

projects/free.yml
https://github.com/victorhaggqvist/AboutIt
=> add AboutIt

projects/free.yml
It is for applications that require dependencies to other applications. It will show a preference to automatically install the dependency Application.
=> IntegrationPreference is added.

projects/free.yml
=> Add: EmailAutoCompleteTextView by @tasomaniac

projects/free.yml
also added Glide for image processing, since it's recommended by google.
=> added few more things

projects/free.yml
An Android project providing easy navigation between a calendar and an agenda
=> Added AgendaCalendarView

projects/free.yml
Add [openalpr-android](https://github.com/SandroMachado/openalpr-android) library.
=> Add openalpr-android library.

projects/free.yml
Stimulate Apple's Force Touch or 3D Touch on Android App with Hover Gesture
=> Add HoverTouchView

projects/free.yml
AndroidTampering is a library to protect your applications against tampering attacks.
=> Add AndroidTampering library

projects/free.yml
The library Restaurant is extension to the Snackbar view available at the Android Design Support Library.
=> Add library Restaurant

projects/free.yml
Hi, I would like to add my library.
Thanks!
=> Add ipcam-view

projects/free.yml
The cube grid animation by android.
=> Add the cube grid animation library.

projects/free.yml
This library is similar to Instagrams peek and pop feature, with a few extra features.
=> Add PeekAndPop library

projects/free.yml
Added the PasscodeView library in 'TextView' & added the 'StepBuilder' plugin in 'IDE plugins'
=> Updated the free.yml with 2 entries

projects/free.yml
Light-weight background processing library.
=> Add TaskQueue library.

projects/free.yml
A library to display version information fragments or dialogs.
=> Add android-versioninfo

projects/free.yml
Underneath the Material Design heading.
It is a library to provide you with all the Material Design resources you need: colours, dimension values, layouts for different components - all to make using Material Design easier.
It also includes some useful custom views such as a PasswordEditText, style for a full-width EditText text field and list item and grid item views - all to meet Material Design guidelines.
=> Added Material Android

projects/free.yml
Add SnackEngage in the SnackBar section
Engage Users with a Snackbar to e.g. rate or translate the app
=> Add SnackEngage

README.md, projects/demo.yml
It's actually a real app available on Play Store, Amazon Store and soon
F-Droid. The source demonstrates how to use the account and sync
frameworks as well how to create services, intent services and the
communication between the components. It also demonstrates access to the
contacts and calendar providers.
=> Add BirthdayCalendar demo project

README.md, projects/free.yml
Simplifies development and provides higher level classes including
fallback (if Chrome isn't available).
=> Add Chrome Custom Tabs helper libraries
